name: xuyang-client

grpc_port: 13831
port: 8081
grpc_example_addr: 192.168.1.102:13831

database:
  host: 127.0.0.1
  port: 30001
  user: root
  password: 123456
  name: hx

logDir: .

golang-consul:
  port: 8500
  host: consul
  token: d



