name: xuyang

grpc_port: 13831
port: 8080
grpc_example_addr: grpc_example:13831

database:
  host: 127.0.0.1
  port: 30001
  user: root
  password: 123456
  name: hx

logDir: .

golang-consul:
  port: 8500
  host: consul
  token: d



